name: Fiji Weather Alerts

on:
  schedule:
    - cron: "0 * * * *"   # Runs at the start of every hour (UTC)
  workflow_dispatch:      # Allows you to click "Run workflow" manually for testing

jobs:
  run-weather:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: Run weather script
        # This section connects your GitHub Secret to your Python script
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOKDISCORDWEATHER }}
        run: python weather_fiji.py
